rust-embedded/svd2rust

README.md
src/lib.rs

`.modify()`: give access to readable bits of the register

---

Cargo.lock
Cargo.toml
ci/run.sh
src/lib.rs
src/main.rs

add support for register arrays

---

ci/run.sh
src/lib.rs

support registers without `fields`

---

ci/run.sh
src/lib.rs

don't expose reserved fields (bit ranges actually)

---

src/generate.rs

closes #65
barely tested. Seems to work though

generate a different type for each peripheral instance

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/generate.rs
src/lib.rs

see commit messages for the rationale
this is a breaking change

change the fields of interrupt::Handlers to pascal case

---

src/generate.rs
src/util.rs

Handling "[PERIPHERAL].[REGISTER].[FIELD].[ENUMERATEDVALUES]" format
for the "derivedFrom" attribute in <enumeratedValues>.
(used https://www.keil.com/pack/doc/CMSIS/SVD/html/elem_registers.html#elem_enumeratedValues as a reference).

Adding support for references to another peripheral

---

.travis.yml
ci/install.sh
ci/script.sh

full test suite

---

ci/script.sh

add regression tests for #92 and #99

---

Cargo.toml

Upgrade Cargo.toml to the latest versions and style

---

appveyor.yml

it seems that we are hitting the cache size limit

appveyor: disable the cache

---

.travis.yml
ci/script.sh
src/generate.rs

fix codegen for the msp430 target
closes #161

add tests for the msp430 and none targets

---

.gitlab-ci.yml
ci/svd2rust-regress/Cargo.toml
ci/svd2rust-regress/README.md
ci/svd2rust-regress/src/errors.rs
ci/svd2rust-regress/src/main.rs
ci/svd2rust-regress/src/svd_test.rs
ci/svd2rust-regress/src/tests.rs

This enables rustfmt, makes seeing what errors happened during `cargo check` easier and some minor other changes.

Improve ci

---

src/main.rs

This change allows the input data to be provided via stdin when no input file is specified.

Allow svd files to be read from stdin

---

ci/script.sh
ci/svd2rust-regress/src/tests.rs
src/generate/device.rs

the former has been removed in the latest nightly

replace the macro_reexport feature with use_extern_macros

---

src/generate/device.rs
src/generate/interrupt.rs

Address build failures on nightly due to lint

---

src/generate/interrupt.rs
src/generate/peripheral.rs
src/generate/register.rs
src/util.rs

More clippy lint fixes which should be uncontroversial

---

src/generate/peripheral.rs
src/generate/register.rs

Fixed some trivial clippy lints

---

src/util.rs

Fix bracket typos when escaping

---

src/generate/device.rs

Working with a LPC1347 board, compilation fails with 
```
pub use cortex_m::peripheral::{CBP, CPUID, DCB, DWT, FPB, FPU, ITM, MPU, NVIC, SCB, SYST, TPIU};
^^^ no `FPU` in `peripheral`. Did you mean to use `MPU`?
```
The [SVD file](https://github.com/ax-rwnd/rust-lpc1347/blob/master/LPC13Uxx_patched.svd) provides the information that no FPU (nor MPU) is present.

Simplistic check if FPU is defined in CPU-block

---

src/generate/device.rs
src/generate/interrupt.rs

see individual commits for details
this is a breaking change

make non cortex-m targets compile on stable

---

src/generate/device.rs
src/generate/interrupt.rs

Allow building on 1.31 (stable)

---

src/generate/interrupt.rs

Implement Copy, Clone, Debug for Interrupt

---

ci/script.sh
ci/svd2rust-regress/src/svd_test.rs
src/generate/device.rs
src/lib.rs

Closes https://github.com/rust-embedded/svd2rust/issues/204

Re-enable tests for RISC-V

---

src/generate/device.rs
src/generate/interrupt.rs
src/generate/peripheral.rs
src/generate/register.rs
src/lib.rs
src/main.rs
src/util.rs

Fixed all remaining clippy lints (except the complexity ones)

---

Cargo.toml
build.rs
src/generate/device.rs
src/generate/interrupt.rs
src/generate/peripheral.rs
src/generate/register.rs
src/lib.rs
src/main.rs
src/util.rs

Edition-2018-ify svd2rust

---

src/generate/register.rs

Simplify modify function from 5 to 2 lines of code

---

src/generate/register.rs

Coalesce write implementation into a single line down from three

---

ci/script.sh
ci/svd2rust-regress/src/main.rs
ci/svd2rust-regress/src/svd_test.rs
src/generate/interrupt.rs
src/generate/register.rs

ed2018 for generated code

---

src/lib.rs

Remove mention of the untagged_unions nightly feature

---

Cargo.toml

Update metadata in Cargo.toml

---

CHANGELOG.md
src/generate/device.rs
src/generate/generic.rs
src/generate/mod.rs
src/generate/register.rs
src/util.rs

Generics part 2 (the easiest part)

field reader

---

CHANGELOG.md
Cargo.toml

Release 0.15.1

---

CHANGELOG.md
Cargo.toml
ci/script.sh
src/generate/device.rs
src/generate/peripheral.rs
src/generate/register.rs

r? @Disasm 
Depends on https://github.com/japaric/svd/pull/74
Instead of #371

Peripheral Cluster defaults

---

src/generate/register.rs

Fix typo in generated doc string

---

.travis.yml

Fix windows msvc build

---

src/generate/device.rs
src/generate/interrupt.rs
src/generate/peripheral.rs
src/generate/register.rs
src/lib.rs
src/main.rs

Use TokenStreams directly instead of Vec<TokenStream>

---

CHANGELOG.md
Cargo.toml
src/generate/peripheral.rs
src/main.rs

Bump dependencies

---

CHANGELOG.md
Cargo.toml

Prepare 0.17.0 release

---

ci/script.sh

https://github.com/rust-lang/rfcs/pull/2843

update msp430 test deps

---

CHANGELOG.md
src/generate/register.rs

fix bug in #537

---

CHANGELOG.md
src/generate/register.rs

offset_calc fix parenthesizing

---

src/generate/register.rs

refix calculate offset

---

.github/workflows/release.yml
CHANGELOG.md

- Execute when new commit in master and attach to pre-release
- Execute when new version tag and attach to release
- Allow manual execution
close #597

ci: add action to build and release binaries

---

CHANGELOG.md
src/generate/register.rs
src/util.rs

sort fields & register sizes

---

CHANGELOG.md
src/generate/generic.rs

doc examples for write

---

CHANGELOG.md
Cargo.toml
src/generate/generic.rs
src/generate/interrupt.rs
src/generate/register.rs

Eq impl & add safety docs

---

CHANGELOG.md
src/generate/register.rs

must_use for writers

---

CHANGELOG.md
src/generate/generic.rs
src/generate/register.rs

initial_write_value for registers with modifiedWriteValues

---

CHANGELOG.md
src/generate/generic.rs

inline set/clear_bit

---

CHANGELOG.md
src/main.rs

Fixes #681 
@newAM Could you test it?

enable exit_on_error

---

CHANGELOG.md
src/generate/register.rs

let readable field fetch doc from svd description

---

CHANGELOG.md
src/generate/device.rs

Fix #760 
I don't see real necessity in these lints. So this PR just removes them.

remove unstable lints

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/generate/array_proxy.rs
src/generate/peripheral.rs
src/generate/register.rs
src/util.rs

support dimName and dimArrayIndex for array names and descriptions

---

CHANGELOG.md
Cargo.lock
Cargo.toml

other changes are breaking, so lets release first

release 0.30.3

---

CHANGELOG.md
src/generate/peripheral.rs

Fix cluster arrays

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/lib.rs

Partial fix for https://github.com/rust-embedded/svd/issues/247

post-serde validation

---

CHANGELOG.md
src/generate/register.rs

cargo doc constants generation

---

ci/svd2rust-regress/src/main.rs
ci/svd2rust-regress/src/svd_test.rs
src/generate/device.rs
src/generate/interrupt.rs
src/generate/peripheral.rs
src/generate/register.rs
src/main.rs
src/util.rs

- fix warnings in regress
- apply clippy suggestions

Make clippy happy

---

CHANGELOG.md
src/generate/peripheral.rs
src/generate/register.rs
src/util.rs

DimSuffix trait

---

CHANGELOG.md
src/generate/register.rs

fix typo: Incorrect mapping of ZeroToSet

---

CHANGELOG.md
src/generate/generic.rs
src/generate/register.rs

implement Debug for Field/BitReader + generic Debug for Reg

---

.github/workflows/ci.yml
CHANGELOG.md
src/generate/device.rs

Fix building without yaml feature

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.lock
Cargo.toml

release 0.34.0

---

.github/workflows/ci.yml
.github/workflows/release.yml
CHANGELOG.md
src/util.rs

normalize paths

---

Cargo.lock
ci/svd2rust-regress/Cargo.toml
ci/svd2rust-regress/src/svd_test.rs

regress with edition 2021

---

CHANGELOG.md
Cargo.lock
Cargo.toml

release 0.36

---

CHANGELOG.md
src/generate/register.rs

See https://github.com/stm32-rs/stm32-rs/issues/1245

fix mismatched-lifetime-syntaxes
