rust-embedded/svd2rust

README.md, src/lib.rs
=> `.write()`: change signature to take a closure that modifies the reset

src/lib.rs
If `width == 32` the left shift overflows, which causes a panic in debug mode. In order to fix this, we increase the mask size to `u64`.
[wrapping_shl](https://doc.rust-lang.org/nightly/std/primitive.u32.html#method.wrapping_shl) doesn't work here since it “removes any high-order bits of rhs that would cause the shift to exceed the bitwidth of the type”. So `1.wrapping_shl(32)` becomes `1.wrapping_shl(0)`, which leads to the wrong mask.
=> Fix overflow for width==32

src/lib.rs
Sanitize field name to prevent conflict with Rust keywords.
=> Sanitize name

src/lib.rs
Registers that have mixed read-only and write-only fields default to read-write access.
=> Default to the case of register read-write access

src/lib.rs
This was a problem for example when generating the map for NVIC on the STM32F303x, where
most registers would be discarded because STIR is listed first, before all ISERx fields.
=> Sort registers by address_offset before checking for overlap.

src/main.rs
Match peripheral name exactly to prevent specification of peripheral such as tim1 accidentally returning peripheral details for tim15 for
instance.
=> Match peripheral name exactly

src/lib.rs
It's successor for https://github.com/japaric/svd2rust/pull/29, sanitize register's name too.
=> Sanitize register's name

src/lib.rs
reset_value is by default output as u32, which sometimes disagrees with the width of the register itself causing a type error on compilation. Patch just removes the u32 suffix.
=> fix reset_value bitness

src/lib.rs
This list of keywords was pulled from the [Rust grammar][1]. This also
changes the sanitize method to take ownership of its argument.
[1]: https://doc.rust-lang.org/grammar.html#keywords
Fixes https://github.com/japaric/svd2rust/issues/54.
=> sanitize all rust keywords

Cargo.lock, Cargo.toml, ci/script.sh, src/lib.rs, src/main.rs
This PR is like #52 but with an alternative write API.
The generated write API looks like this:
``` rust
#[derive(Clone, Copy)]
#[repr(C)]
pub struct DirW {
bits: u32,
}
pub struct DirWPin0<'a> {
register: &'a mut DirW,
}
impl<'a> DirWPin0<'a> {
pub fn input(self) -> &'a mut DirW {
const MASK: u32 = 1;
const OFFSET: u8 = 0u8;
self.register.bits &= !((MASK as u32) << OFFSET);
self.register.bits |= 0u32 << OFFSET;
self.register
}
pub fn output(self) -> &'a mut DirW {
const MASK: u32 = 1;
const OFFSET: u8 = 0u8;
self.register.bits &= !((MASK as u32) << OFFSET);
self.register.bits |= 1u32 << OFFSET;
self.register
}
}
impl DirW {
#[doc = "Bit 0 - Pin 0."]
pub fn pin0(&mut self) -> DirWPin0 {
DirWPin0 { register: self }
}
..
}
```
Instead of exposing a method that takes an enum to modify a …
=> enum based API (alternative write API)

src/generate.rs
Rust representation doesn't even guarantee keeping the order, I've found
some registers in the wrong place and this fixed it.
=> Using C layout for RegisterBlock structs

CHANGELOG.md, Cargo.lock, Cargo.toml, src/generate.rs
i.e. if WriteConstraint::Range covers the whole range of values that the
bitfield can take
This seems to work for the use case I had in mind
thoughts @cwoodall?
=> make W.bits safe if WriteConstraint indicates so

.rustfmt.toml, CHANGELOG.md, Cargo.lock, Cargo.toml, build.rs, src/generate.rs, src/main.rs, src/util.rs
instead re-export the cortex-m crate's API
=> don't generate an API for core peripherals

src/generate.rs
Or else the resulting file will not compile.
Fixes #77.
=> Do not emit `mod interrupt` if there aren't any defined

src/generate.rs
This is only done for Access::ReadWrite because writing the reset
value to write-only registers does not seem like it has any potential
use at all.
Fixes #19.
=> Add a .reset() method as a short-hand for .write(|w| w)

src/generate.rs
For TM4C, interrupts cannot be automatically, easily, or possibly
at all (since SVD does not define how interrupt sharing should work)
be associated in an 1:n fashion to peripherals.
Since svd2rust does not really care where the interrupts are in SVD,
I simply emit a fake peripheral with the complete list of interrupts
(but no registers at all). This peripheral thence does not show up
in the generated code, except in `mod interrupts`.
The SVD specification permits this behavior (the `<registers>`
element is marked as `0..1` occurrences; nowhere in the text
I could find a requirement that a peripheral have registers;
and it passes schema validation).
=> Do not reject peripherals without registers

src/generate.rs
This happens for a write constraint specifying the range 0..2^32-1.
=> Fix a possible shift past integer width

src/generate.rs
This is my attempt to fix #87.
Code is still being generated for reserved, but this reduces most cases.
=> Avoid generating code for reserved fields and enumerated values.

src/generate.rs, src/lib.rs, src/util.rs
This makes using such fields significantly more ergonomic, as
previously they would have been `u8`s, leading to unnecessary
conversion and silent truncation in downstream code.
The `bool` writers are never unsafe because it is meaningless
to have a writable field that only admits one (or worse, zero)
valid values.
=> Generate `bool` accessors for single-bit fields

src/generate.rs
follow up of #84
cc @whitequark
=> add is_set / is_clear methods

src/util.rs
ST use square brackets in some fields where the field has been extended to have more bits elsewhere in the register, so the field ends up with a name like OC2M[3]:
The resulting code is `struct Oc2m[3]R` which of course won't compile. Adding square brackets to the blacklist gives `struct Oc2m3R` instead which works and seems reasonable.
=> Add square brackets [ and ] to BLACKLIST_CHARS

Cargo.lock, Cargo.toml, src/generate.rs, src/util.rs
Fixes #76.
Depends on https://github.com/calebmer/inflections/pull/2.
=> Normalize SVD names to upper case where they were to pascal case

.travis.yml, Cargo.lock, ci/script.sh
we now at least test one device per vendor in the SVD database
cc #45
=> extend test suite

ci/script.sh, src/generate.rs
fixes #102
cc @whitequark
waiting for #104 to make sure this doesn't break other stuff
=> make sure that the register size is always a power of 2 >= 8

src/generate.rs, src/util.rs
`set()` -> `set_bit()`
`clear()` -> `clear_bit()`
`is_set()` -> `is_bit_set()`
`is_clear()` -> `is_bit_clear()`
Also adds these names to the list of reserved keywords along with `bit` and `bits`
so that they are suffixed with an underscore if used as a variant name.
Also causes the `set_bit()` and `clear_bit()` methods to be added even if the field has an enumeratedValues.
#99 #92 @whitequark
=> Rename bit read/write methods.

src/generate.rs, src/util.rs
Ugh, I know we just merged #109 but after using it for a couple of days I think it really should have been `bit_is_set()` rather than `is_bit_set()`. I'm happy with `set_bit()` and `clear_bit()` though, they seem natural:
```rust
usart3.cr3.dmat().set_bit();
while usart3.isr().tc().bit_is_clear() {}
if usart3.isr().ore().bit_is_set() {
...
}
```
As an added bonus, this way around we don't have to reserve the `bit_set`/`bit_clear` variant names, because it will no longer clash.
What do you think?
=> Rename is_bit_clear to bit_is_clear, is_bit_set to bit_is_set

ci/script.sh, src/generate.rs, src/main.rs
@pftbest has been doing a great work at getting msp430 support at the
[cortex-m-quickstart] level by porting a bunch of cortex-m-* crates to msp430.
They also have a fork of svd2rust that can generate msp430 device crates from
msp430 SVD files.
[cortex-m-quickstart]: https://github.com/japaric/cortex-m-quickstart
In parallel @ahixon has been working with bare metal Cortex-A processors and
they also want to be able to use svd2rust to generate a device crate for their
Cortex-A processor.
This RFC / PR is about adding multiarch support to svd2rust to support these two
cases.
As @ahixon suggested this RFC proposes moving non Cortex-M bits from the
`cortex-m` crate into a common crate: the [`mcu`] crate. Both the `cortex-m`
crate and the `msp430` crate, its MSP430 counterpart, will re-export …
=> [RFC] multiarch support for svd2rust

src/generate.rs
the last minute fix from #123 removed them from this struct
=> struct Peripherals should include derived peripherals

appveyor.yml, src/generate.rs
A workaround for https://github.com/japaric/cortex-m/issues/19
=> Fix duplicated exception handlers.

src/generate.rs
Add an extra function as a possible solution for
https://github.com/japaric/cortex-m-rtfm/issues/39
=> Weak aliases should only point to defined symbols.

src/generate.rs
the global_asm! block, which is behind the "rt" feature, contains ARM specific
assembly that won't compile on x86 so we make that conditional (ARM only) and
provide a different DH_TRAMPOLINE when compiling for x86
=> hack to make device crates compilable on x86

src/generate.rs
Fixes japaric/cortex-m-rtfm#42
~~Note that this will make all generated crates that target an armv6
device fail to compile unless they add a build script enabling the added
`cfg`.~~ (this is no longer the case, everything should Just Work™)
=> Use far-ranged jumps for DH_TRAMPOLINE

Cargo.lock, src/generate.rs
This makes the generated crates build in more cases.
=> Assume ARMv6 when `<cpu>` section is missing

src/generate.rs, src/util.rs
The two main reasons behind this change are ensuring that the numbers
(mostly addresses, masks and default values) line up with the datasheet
for easier searching and verification since those are pretty much always
expressed in hexadecimal. The other reason being clippy now complains
about long numeric literals (without seperators) being hard to read -- I
agree.
=> Implemented new functions to format literals as seperated hex idents

src/generate.rs
`ident` is not sufficient, as it won't allow something like
`::module::Type`.
=> Change type of `$lty` argument to `ty`

.rustfmt.toml, .travis.yml, Cargo.toml, build.rs, ci/install.sh, ci/script.sh, src/generate.rs, src/main.rs, src/util.rs
See this RFC for details: japaric/svd2rust#157
With this change device crates will need to depend on a version of the cortex-m crate that includes japaric/cortex-m#65
=> Peripherals as scoped singletons

src/generate.rs
E.g. this from tm4c123x.svd generated by dslite2svd:
```
<field>
<name>VREF</name>
<description>Voltage Reference Select</description>
<lsb>0</lsb>
<msb>0</msb>
<access>read-write</access>
<writeConstraint>
<useEnumeratedValues>true</useEnumeratedValues>
</writeConstraint>
<enumeratedValues>
<enumeratedValue>
<name>INTERNAL</name>
<description>VDDA and GNDA are the voltage references</description>
<value>0x0</value>
</enumeratedValue>
</enumeratedValues>
</field>
```
=> Add missing unsafe qualifier on 1-bit enumerated fields

src/generate.rs
This supersedes @lucasbrendel's similar PR #153 and fixes #150.
Per the [SVD spec](http://arm-software.github.io/CMSIS_5/SVD/html/elem_special.html#dimElementGroup_gr), dimIndex is not required:
> By default, \<dimIndex\> is a value starting with 0.
> Remark: Do not define \<dimIndex\> when using the placeholder [%s] in \<name\> or \<displayName\>.
I interpret this as the element being optional with "%s" and not allowed with "[%s]" (this change does not reject the latter). Atmel SAMD21 SVDs use "%s" with no dimIndex for 0-indexed arrays.
This also tests that dimIndex is sequential and numeric in a single pass without allocating temporary vectors, and fixes the typo adresses -> addresses.
=> Handle missing dimIndex on registers

src/lib.rs, src/main.rs, src/target.rs
This makes it nice and easy for `cargo build` scripts to generate the source for SVD files, similar to the way that `bindgen` works.
For an example take a look at <https://github.com/dfrankland/mk20d7/blob/master/build.rs>
=> Expose internals to lib

src/lib.rs, src/main.rs, src/target.rs
This reverts commit 93148049b56d15af3a1f598d1df7ad120ef8449e.
I'd rather not make this API public; it forces semver on us and we would have to bump the minor
version more often. For example, we would have to bump the minor version whenever we change the API
of `generate::{interrupt,..,register}::render`, which happens to be a pretty big API surface as it
includes structs from the `svd` and the `syn` crates so if we (minor version) bump any of those
dependencies then we have to bump the minor version of `svd2rust` as well.
Also the more often we bump minor versions the more work we give to device crate authors: now when
they re-generate their device crates they have to check if the minor version actually broke the
generated API or if it just was due to change in the API of `svd2rust`, the …
=> Revert PR 201 "Expose internals to lib"

.gitignore, src/generate/device.rs, src/generate/peripheral.rs, src/main.rs
I want to get a complete working build for ATSAMD21 (https://github.com/rust-lang-nursery/embedded-wg/issues/61) so I'm taking a stab at that.
* Introduced a `FieldRegion` helper to reason about overlapping regions
* If overlaps are detected, a `union` container is emitted
* If the only item in a `RegisterBlock` is a union, that `RegisterBlock` is emitted as a union
* Otherwise: we generate a name for the union field by either taking the shortest common prefix of the union's alternates or the shortest register name (depending on type name conflicts). If that doesn't work just pick an artificial name like `u1`.
* If the starting address offset of elements in a union are not all the same, we don't have a way to emit padding for them today.  We will emit a warning (and bad code) in that case …
=> Emit unions for overlapping/overloaded registers

src/util.rs
These characters occur in [the .svd file for NXP LPC13xx](https://github.com/posborne/cmsis-svd/blob/master/data/NXP/LPC13xx_svd_v1.svd).
=> Add `'/'`, `' '` to `BLACKLIST_CHARS`

.travis.yml, Cargo.toml, ci/install.sh, ci/script.sh, src/generate/device.rs, src/generate/interrupt.rs, src/lib.rs, src/main.rs
This is still missing some stuff:
- svd2rust must now generate an interrupts.x linker script and a build script that puts the linker script somewhere the linker can find it. See japaric/stm32f103xx#24 for a sample of what those files look like.
- we have to decide how to organize the svd2rust output. It probably makes sense to generate 3 files on $PWD (lib.rs, build.rs, interrupts.x) for Cortex-M and a single lib.rs for the other targets.
- I probably broke the other targets; need to test them
=> cortex-m: generate code that compiles on stable

src/generate/peripheral.rs
PascalCase doesn't work when we have overloaded registers named
`FOO_11` and `FOO1_1`.
This happens in
* Freescale MKL81Z7
* Freescale MKL82Z7
* Freescale MK81F25615
* Freescale MK82F25615
on `LTC0_PK*` registers.
I'm not sure if `{ident}Union` is the best choice anymore as `FOO_BARUnion` doesn't seem as good as it possibly could be.
cc @jamesmunns @wez
=> Change inflection on unions

src/generate/interrupt.rs, src/generate/peripheral.rs, src/generate/register.rs, src/util.rs
... in docstrings. This function takes care to not add another level of
escaping in case a docstring contains already escaped brackets.
Closes #232.
Apologies to @Nicoretti for not noticing his PR earlier. However I do
think it is important to not escape properly escaped brackets again,
this is only meant in cases the author failed to do so.
=> Added util::escape_brackets function to escape unescpad brackets

src/generate/device.rs, src/generate/interrupt.rs, src/lib.rs
this is a breaking change because
- it bumps the cortex-m-rt version requirement to v0.6.4
- it changes the behavior of the `<device>::interrupt` item. This item was a
bang macro and now has become an attribute.
=> re-export the `interrupt` attribute

src/generate/device.rs
It only makes sense to export interrupt if the interrupt! macro is
exported as well, since it's the only thing using it.
Fixes #260
=> Only export Interrupt as interrupt when 'rt' is enabled

ci/script.sh, src/main.rs
NOTE: I believe there is still documentation that will need to be updated to represent this. I wanted to make sure my CI changes still work without the other changes (like Cargo.toml) after pulling these changes
=> Consistent svd2rust output

ci/script.sh
Im trying to find a way to speed up ci as were currently failing due to 50min timeout
It appears its the freescale entry in the matrix, most likely because it has 133 svds that it tests, thats 1/5 of the total svds upstreamed there.
It doesnt actually look like our code is the issue. We seem to run in a second or so. It seems like 
maybe cargo check and rustfmt split the time. Why rustfmt at all? its probably on average 15 seconds * 133 svds, that would be a dent 
Can someone bors this and see what happens?
=> ci: remove rustfmt for speed

src/lib.rs, src/main.rs, src/util.rs
This change implements the minimal API described in #207 to allow downstream build.rs scripts to generate the svd2rust output.
=> Provide library access to code generation

ci/script.sh, src/lib.rs
Now, `cargo test` still doesn't actually run any tests, but at least it
doesn't report a failure.
Fixes #271
=> Disable broken doctests so cargo test works.

src/generate/register.rs
The enums are just values so this should do no harm, and it helps
building interfaces around the peripherals that do validation or
otherwise pass those values around.
Closes: https://github.com/japaric/svd2rust/issues/135
=> Derive common traits for write enums like for read enums

src/generate/interrupt.rs
Closes https://github.com/rust-embedded/svd2rust/issues/280
=> Generate documentation for the interrupt macro

.travis.yml, ci/before_deploy.sh, ci/install.sh, ci/script.sh
this removes the Linux GNU targets used to produce binaries but we still have
the MUSL builds which will work everywhere because they statically linked
binaries
=> CI: use Cargo instead of Cross

src/generate/peripheral.rs, src/main.rs
This just removes two rustc warnings about an unused `mut` and redundant `use`.
=> Fix rustc warnings.

ci/script.sh, src/util.rs
Some registers on K210 chip are 64-bit, so it's better to declare them as u64 in SVD for the reasons mentioned here: https://github.com/riscv-rust/k210-pac/issues/1#issuecomment-489311245
At the moment, svd2rust forbids 64-bit register declarations. This PR fixes this.
This change can cause silent bugs on platforms without 64-bit memory access operations due to the need for proper access sequence to 64-bit registers with two 32-bit accesses.
Closes https://github.com/rust-embedded/svd2rust/issues/289
=> Add support for 64-bit registers

ci/script.sh
If svd2rust fails its always useful to get some information about the where and why
=> Added RUST_BACKTRACE=1 to enable backtraces

src/generate/device.rs
Very simple PR! :)
This permits actually-unsafe use of the steal method, and avoids divergent behavior between debug and release modes.
=> Remove debug assert from Peripherals::steal

src/generate/register.rs
Struct initialisations don't need to repeat field names if they're equal
to a local variable.
=> Remove some noise in the generated code

src/generate/register.rs
cc @therealprof 
Example:
```rust
pub unsafe fn bits(self, value: u8) -> &'a mut W {
self.w.bits &= !(0x1f << 8);
self.w.bits |= ((value as u32) & 0x1f) << 8;
self.w
}
pub fn dbl(&self) -> DBLR {
let bits = ((self.bits >> 8) & 0x1f) as u8;
DBLR { bits }
}
```
=> Remove Mask offset consts

src/generate/register.rs
move `reset_value` to be public method of register struct (not `W`).
It's breaking change, but I think this can't break existent code.
=> move reset_value

Cargo.toml, src/generate/peripheral.rs, src/generate/register.rs, src/lib.rs, src/main.rs, src/util.rs
Use 2 last commits from #256 :
https://github.com/rust-embedded/svd2rust/pull/256/commits/b6d2c9a8076198d8579a9fe2525605991ef7a424 and https://github.com/rust-embedded/svd2rust/pull/256/commits/b7965db513554e2521000845dd0733bfad930c44
=> Use svd-parser 0.7 and Edition 2018

src/generate/device.rs, src/generate/peripheral.rs
Implemented by @wez this PR replace untagged unions with functions for access to alternate registers.
Closes #230, #218, https://github.com/stm32-rs/stm32-rs/issues/149 .
=> No unions3

src/generate/peripheral.rs
First three commits from #256 .
=> register Derived from

src/generate/peripheral.rs
Fix misusing cluster size tag.
Close #299 .
=> fix cluster size

src/generate/register.rs, src/util.rs
Currently doesn't enforce the write-once nature of the registers, but
treats them as write-only.
=> Add support for `Access::WriteOnce` registers

src/generate/peripheral.rs, src/generate/register.rs
This PR basically reverts #141 and plays with inline markers for some large dev build binary size gains
=> improve dev builds

src/generate/peripheral.rs
=> DRY: We can just use &Self::Target for deref impl

src/generate/device.rs, src/generate/interrupt.rs, src/generate/peripheral.rs, src/generate/register.rs
Using `/// something` in a quote! block generates
`#[doc = r" something"]`
need to use `///something` to get the more appropriate
`#[doc = r"something"]`
instead
=> Prevent quoted doc strings from generating extra blanks at the beginning

src/generate/register.rs
=> Refactor fields

src/generate/register.rs
Reduces build size by quite a bit in dev builds but to my surprise also
helps in optimised builds using set_bit/clear_bit indirectly via HAL
impls.
Closes #334
=> Also always inline set_bit/clear bit

CHANGELOG.md, src/generate/peripheral.rs, src/generate/register.rs, src/util.rs
Right use of cluster.size + better support of 64bit registers.
See #299 , partially closed in #325 .
Not tested yet.
=> sizes, 64bit

CHANGELOG.md, src/generate/peripheral.rs, src/generate/register.rs, src/main.rs
By manually iterating over the Vec<Token> when writing out to lib.rs we
can insert new lines after each token. In addition we split up some
of the inner quote repetition operator uses into regular iteration, too,
to generate individual Tokens. This changes a typical lib.rs file from 2
to 20k lines (200k after rustfmt) which should help a lot to prevent
tools (like rust when errors happen) from going insane and makes the
files a lot more directly usable without having to rustfmt all the time.
=> Don't use quote concats to munge the Vec<Tokens> into one huge string

ci/script.sh
Freescale is constantly holding up CI (which is bad) and every now and
then even bumping into time limits. Worst of all, pretty much all of the
SVDs are outdated since that devision of Freescale was acquired by NXP a
long time ago. So let's cut down the outdated list of test targets by a
few members of each family and activate some NXP test targets instead
which should work now, but didn't before.
=> Cut down excessive test list of "Freescale" targets and add new ones

CHANGELOG.md, src/generate/register.rs
Also this rectifies many of the tons of
https://rust-lang.github.io/rust-clippy/master/index.html#identity_op
lints we're getting.
=> Join the bits muching into a single line to improve dev builds

CHANGELOG.md, src/generate/generic.rs, src/generate/register.rs
Restore access to `enum`'s by `variant` method that return `enum FIELD` when possible or `Variant`.
Also replace `_to_bits` method in writer with trait.
So now enums for reader and writer are identical (when they don't use different values for read and write) and can be replaced by one.
See #353 .
=> add variant to reader

CHANGELOG.md, src/generate/generic.rs, src/generate/register.rs
=> Generic Part1

Cargo.toml, src/generate/device.rs, src/generate/generic.rs, src/generate/mod.rs, src/lib.rs, src/main.rs
Adds option `-g` which when enabled store contents of `generic.rs` in separate file.
It's useful for common crates like `stm32f1` where one crate for several `pac`s.
Uses `syn::parse` instead of vector of `quote!`.
=> separate generic mod

CHANGELOG.md, src/generate/generic.rs, src/generate/register.rs, src/lib.rs
Add more docs as @Disasm proposed.
Restore `unsafe` on `W::bits()` I somewhere lost.
Don't generate `write` if `reset_value` is not present. #258
=> fix docs+examples, work without reset, fixes

CHANGELOG.md, src/generate/peripheral.rs, src/generate/register.rs
SVDs available for DA1469x from https://www.keil.com/dd2/pack have few registers with missing `<description>` and this causes svd2rust to crash.
This PR enables to continue with a dummy description  and print name of the
problematic register instead of just bailing out.
=> Fix crash on missing register description in SVD file

src/generate/generic.rs, src/generate/register.rs
=> From instead of ToBits

src/util.rs
Example: "normally or power-up" gave "NORMALLYORPOWER-UP" which doesn't work.
=> Sanitize names from dashes

CHANGELOG.md, src/generate/register.rs
=> enum descriptions

src/generate/register.rs
=> desc enum fix

CHANGELOG.md, src/generate/interrupt.rs
The old 32 bit vectors caused linker errors when building for MSP430. This change fixes the errors.
=> Make interrupt vector for MSP430 16 bits instead of 32 bits

src/generate/peripheral.rs
=> Add `#[inline(always)]` to deref implementations.

CHANGELOG.md, src/generate/register.rs
enums are now in C-style with `#repr(..)`
Should slightly reduce code size in debug mode when enums are used.
r? @Disasm
=> use repr(fty) for enums

CHANGELOG.md, src/generate/device.rs
Hi! :wave: Thanks for this awesome project!
I've run into a build error generating bindings for the [psoc6-pac](https://github.com/psoc-rs/psoc6-pac). Here's a example of one of the many build failures:
```
error: structure field `data_list_sent_update__status` should have a snake case name
--> src/ble.rs:187:9
|
187 |     pub data_list_sent_update__status: self::blell::DATA_LIST_SENT_UPDATE__STATUS,
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: convert the identifier to snake case: `data_list_sent_update_status`
```
This issue is caused by `#![deny(warnings)]` and should be fixed by adding the `#![allow(non_snake_case)]` exception. There may be alternative fixes, I'm open to suggestions!
=> Ignore non snake case types that can exist in SVD files

src/generate/interrupt.rs
Make the Interrupt enum descriminant match the interrupt nr directly. This allows simplifying Interrupt::nr from being a complicated match to a simple cast to an u8.
According to #370, this should lead to a code reduction of as much as 304 bytes.
Fixes #211
Fixes #370
=> Simplify Interrupt::nr

.travis.yml, README.md
We're now documenting an (arbitrarily chosen) MSRV of 1.37.0 and testing
it in CI while also making nightly tests informational only.
=> Adjust CI to test MSRV and allow nightly to fail

src/generate/register.rs
IMPORTANT. Requires [Rust 1.37](https://blog.rust-lang.org/2019/08/15/Rust-1.37.0.html#referring-to-enum-variants-through-type-aliases)
=> simplify enum derive

src/generate/device.rs, src/generate/interrupt.rs, src/generate/register.rs
=> more TokenStream extend

src/generate/peripheral.rs
=> Round up when calculating register size in bytes

src/main.rs
=> Simplify the output code a bit more for another slight speedup

src/generate/register.rs
=> Deduplicate some code and move some out of the inner loop

src/generate/peripheral.rs, src/generate/register.rs, src/util.rs
=> replace_suffix

.travis.yml, README.md
Part of [wg/#445](https://github.com/rust-embedded/wg/issues/445).
svd2rust already has its MSRV documented and tested, but @adamgreig suggested updating it to use the standard wording. Since this is a special case in that the MSRV applies to the generated code, not svd2rust itself, the standard wording doesn't fully apply, so I changed it in a (hopefully) sensible way.
An open question is: Should we also document the MSRV of svd2rust itself? Looking at how the CI works, currently it's implicitly guaranteed to be the same version als the MSRV for the generated code, so we could just extend the note in the README to also include svd2rust itself.
=> Use standard wording for the MSRV note

CHANGELOG.md, Cargo.toml, src/errors.rs, src/generate/device.rs, src/generate/interrupt.rs, src/generate/peripheral.rs, src/generate/register.rs, src/lib.rs, src/main.rs, src/util.rs
https://github.com/rust-embedded/svd/pull/98
=> `anyhow` Error

src/lib.rs, src/util.rs
Remove unnecessary coercions to 'String' + small fixes to doc comments
-------------------------------------
Thank you for reviewing this PR 😸
=> Remove unnecessary coercions to 'String' + small fixes to doc comments

.github/workflows/ci.yml, .github/workflows/clippy.yml
=> Use GitHub actions for CI

src/generate/peripheral.rs
This contains two commits, the first is a simple typo fix. The second ensures that the complete-pathed type name is generated for clusters.
=> Cluster name qualification

.github/workflows/ci.yml, ci/script.sh, ci/svd2rust-regress/README.md, ci/svd2rust-regress/src/svd_test.rs, ci/svd2rust-regress/src/tests.rs, src/generate/device.rs, src/generate/interrupt.rs, src/lib.rs, src/main.rs, src/util.rs
Adding support for ESP32 as used in new pull requests on https://github.com/esp-rs.
ESP32 has 2 level interrupt handling. First level in the cores. Second level in the periphery/software.
=> Add ESP32 support

ci/script.sh, ci/svd2rust-regress/src/svd_test.rs, ci/svd2rust-regress/src/tests.rs, src/generate/device.rs, src/generate/interrupt.rs, src/lib.rs, src/main.rs, src/util.rs
This PR renames ESP32 (SOC name) to XtensaLX6 (CPU name) to align to convention of other platforms.
It also adds seperate xtensa-lx6-rt and xtensa-lx6 support (instead of just xtensa-lx6-rt).
=> Rename ESP32 to XTensaLX6 and split crate into rt and base

src/generate/register.rs
```
warning: unnecessary braces around block return value
--> src/lib.rs:22188:62
|
22188 | pub fn variant ( self , variant : HSEBYP_A ) -> & 'a mut W { { self . bit ( variant . into ( ) ) } } # [ doc = "HSE crystal oscillator not bypassed" ]
|                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove these braces
```
=> Get rid of a boatload of unnecessary braces warnings

CHANGELOG.md, src/generate/device.rs, src/generate/interrupt.rs, src/generate/peripheral.rs, src/generate/register.rs, src/lib.rs, src/main.rs, src/util.rs
No need to maintain extern crate imports anymore
=> Use and generate code for Edition 2018 only

CHANGELOG.md, src/generate/peripheral.rs
cc https://github.com/rust-embedded/cortex-m/pull/235
=> Add associated const ptr `PTR` to each peripheral RegisterBlock

src/generate/register.rs
As I went to start poking around `src/generate/register.rs`, I got confused by a handful of variable-name-containing variable names.  This is an attempt to make things a bit clearer by making the names more unique across the file and consistent with the variable names contained within.
=> Clarify some generate variables by renaming

src/generate/generic.rs, src/generate/register.rs
Part 1 of #463.
- Publishes the register spec zero-sized type and moves all relevant register traits to that struct, which fixes #459 and improves generated documentation.
- Removes the extra type parameter on `Reg`, making the register spec the sole authority on the shape of the register (but not its address).
One thing that's changed since the previous PR, this renames the spec struct so that it won't cause a conflict on NXP, Freescale, and possibly other architectures.  I've gone with `register::REGISTER_SPEC` since that seems reasonably clear and I can't think of how it would cause a conflict (but I'm ready to be proven wrong since I've tried several ideas only to be stymied by various architectures' oddball register naming patterns).
I'd prefer the spec to be in the parent module, …
=> Register spec & traits

src/generate/peripheral.rs
Part 3 of #463, builds on #465.
- Removes generated use of the register type aliases in favor of directly referencing `Reg<REGISTER_SPEC>`.  I think this helps clarify how the generated and generic types work together.
No breaking change concerns on this change set.
r? @burrbull
=> Avoid register type aliases

src/generate/generic.rs, src/generate/register.rs
Part 2 of #463, builds on #464.
- Wraps register reader/writer and field readers in newtype wrappers, which significantly improves the documentation output.
Again there's some minor potential for breaking changes:
- If users named the complete type of the previous type alias, it would break.  It seems more likely that they would use the alias, which will silently upgrade to a reference to the newtype.
r? @burrbull
=> Accessor newtypes

CHANGELOG.md, ci/script.sh, src/generate/interrupt.rs, src/lib.rs
This also removes the `bare-metal` dependency from PACs created for
MSP430, as requested in
https://github.com/rust-embedded/svd2rust/pull/455#issuecomment-665214017
=> Rework `Interrupt` enum for MSP430

src/generate/generic.rs
I'm developing code that's general across AVR chips.  I'd like to depend on the shared parts of Rahix/avr-device (see https://github.com/Rahix/avr-device/pull/44).  When compiling without any specific device feature enabled, there are no users of the `FieldReader::new` method.  This PR skips the lint for this case.
This is somewhat related to #427 but not exactly.
=> Allow unused FieldReader

src/generate/peripheral.rs
As we use `vcell` to access register contents, we don't need mutable references for this.
=> Remove `_mut` version of alternate register access function

src/generate/register.rs
Previously, the descriptions for fields were only listed on the docs for the accessor methods on the `R` and `W` structs.  This adds the descriptions to the field accessor structs so they appear on the register module page, too.
=> Improve documentation on generated registers and fields

src/generate/generic.rs
Otherwise, a call to `bits` in the closure passed to `write`/`modify` in a function where the register is bound only on the `Writable` trait will fail to typecheck.
This only causes an issue for code written to be generic over a `Writable` register, so I suspect I'm the only one that's so far been bitten by the bug.  In any case, apologies for shipping broken code!
=> Writable::Writer needs DerefMut trait bound

ci/script.sh, ci/svd2rust-regress/src/svd_test.rs, ci/svd2rust-regress/src/tests.rs, src/generate/device.rs, src/generate/interrupt.rs, src/lib.rs, src/main.rs, src/util.rs
The xtensa runtime and device crates have been merged into a single device and runtime crate, feature gating the CPU features.
* s/XtensaLX6/XtensaLX/g
* s/"xtensalx6"/"xtensa-lx"/g
* Replaces lx6 with the generic lx crate
* Updates the CI script accordingly
=> Use xtensa-lx

ci/svd2rust-regress/Cargo.toml, ci/svd2rust-regress/src/svd_test.rs
This bumps the arch dependencies to the current level, removes the
"const-fn" flag support and uses newer reqwest and rayon dependencies
to get rid of some 50 crate dependencies.
=> Update svd2rust-regress once again

src/generate/register.rs
derivedFrom FieldReaders should always be a type alias for the base FieldReader, rather than each their own newtype.
~I believe this fixes #474, however I'm having trouble getting a working development environment set up for the `esp32` project.~
~@MabezDev, would you mind giving this a spin and posting a diff of the generated code?~
Figured out my issue, the generated code looks good, e.g.:
```diff
diff --git a/src/rtccntl/wdtconfig0.rs b/src/rtccntl/wdtconfig0.rs
index 6851bff..089e4e1 100644
--- a/src/rtccntl/wdtconfig0.rs
+++ b/src/rtccntl/wdtconfig0.rs
@@ -186,19 +186,7 @@ impl<'a> WDT_STG0_W<'a> {
#[doc = ""]
pub type WDT_STG1_A = WDT_STG0_A;
#[doc = "Field `WDT_STG1` reader - "]
-pub struct WDT_STG1_R(crate::FieldReader<u8, WDT_STG1_A>);
-impl WDT_STG1_R {
-    pub(crate) fn …
```
=> Fix derivedFrom enumerated values

src/generate/peripheral.rs, src/generate/register.rs, src/util.rs
=> Fix a ton of clippy lints

src/generate/generic.rs
=> fix W::bits signature

src/generate/generic.rs
To guarantee that the register has the proper layout so that the [cast](https://github.com/rust-embedded/svd2rust/blob/971814070cd7be848d3c6524734192903de66866/src/generate/peripheral.rs#L63) of an integer to a `*const RegisterBlock` is sound.
Note that this is necessary but not sufficient.  The underlying `VolatileCell` also currently uses the default repr.  There is an open [issue](https://github.com/japaric/vcell/issues/5) and [PR](https://github.com/japaric/vcell/pull/6/files) to address the concern.
=> Add repr(transparent) to Reg struct

CHANGELOG.md, ci/script.sh, ci/svd2rust-regress/src/svd_test.rs, src/generate/interrupt.rs, src/lib.rs
This eliminates the bare-metal and cortex-m-rt dependencies for Cortex-M
and thus changes CI and svd2rust-regress accordingly.
Replaces #455
=> Implement new InterruptNumber trait from next cortex-m release

ci/script.sh, ci/svd2rust-regress/src/svd_test.rs, src/lib.rs
`src/generate/generic.rs:53` contains an `as_ptr()` call on a vcell.
This was only added in `vcell` v0.1.1 (since yanked).
Thus, the generated crates only build with vcell v0.1.2
=> Update the min `vcell` version to v0.1.2

src/generate/interrupt.rs
There might be more we can do here but this simple fix should at least stop us using `cortex-m` for targets other than `cortex-m`.
cc @Rahix
=> Only use cortex-m when target is cortex-m. Fixes #482.

src/generate/peripheral.rs, src/util.rs
This PR addresses two issues encountered when attempting to process the svd file [here](https://raw.githubusercontent.com/renesas/fsp/master/ra/fsp/src/bsp/cmsis/Device/RENESAS/SVD/RA.svd).
1.  The SVD file defines a cluster in the 'R_GPT_ODC' peripheral that derives from a sibling cluster.  AFAICT from the SVD schema, this is allowed, and we should expand the cluster definition in the same way registers are handled.
2.  The SVD file contains many `EnumeratedValue`s that are "reserved", but aren't filtered out because they're named "other".  They have an `<isDefault>` child element, which is mutually exclusive with the `<value>` child element according to the SVD schema, i.e. they don't represent a value that we would want to define in the generated code, and so can be skipped.
When …
=> Expand derived clusters

src/generate/register.rs
Currently, an `enumeratedValue` is ignored if (and only if) it's name matches "reserved", and all remaining `enumeratedValue`s are expected to have a `value` child element.  However, the SVD schema allows an `enumeratedValue` to contain *either* a `value` element or an `isDefault` element.  When `svd2rust` hits an `isDefault` element that isn't named "reserved", an error is thrown.
In general, filtering these out should be safe, as they don't represent specific values that can be assigned to a field, but rather a *range* of values.  The ability to read and write such arbitrary values is already handled with the `bits()` method defined on field readers/writers.  The one corner case, however, is for fields with only a *single* `enumeratedValue` which has an `isDefault` child element. …
=> Fix handling of `isDefault' `enumeratedValue's

CHANGELOG.md, src/generate/peripheral.rs
This allows structs which hold peripherals to `#[derive(Debug)]`
=> add debug trait

CHANGELOG.md
=> Update CHANGELOG for #485 and #486

src/generate/peripheral.rs
Fixes #249
Tested on following test svd: https://gist.github.com/theli-ua/a1b9c17e94442fbd56c774bb504795a0
=> Fix type path for cluster fields. Allows nested clusters

src/generate/peripheral.rs
This is a followup to https://github.com/rust-embedded/svd2rust/pull/489 , this time for arrays
=> Fix type paths for arrays of nested clusters

.github/workflows/ci.yml, CHANGELOG.md, ci/script.sh, ci/svd2rust-regress/src/main.rs, ci/svd2rust-regress/src/svd_test.rs, ci/svd2rust-regress/src/tests.rs, src/generate/device.rs, src/generate/interrupt.rs, src/util.rs
Hi all,
Willing to add some basic support for MIPS cores? This patch enables the Peripheral Singleton. I use svd2rust to create PACs for PIC32MX microcontroller.
Best regards,
Stephan
=> Mips target

CHANGELOG.md, src/generate/generic.rs, src/generate/register.rs
As each  `FieldReader` now has `bits` method, I think it is not an issue.
=> Remove useless `Variant`, use Option instead

.github/workflows/changelog.yml
=> Add CHANGELOG.md entry checker to GHA workflows

CHANGELOG.md, src/generate/device.rs, src/lib.rs
The -g option emits a separate file called generic.rs to split the generic code from the peripherals.
Right now the -g option requires a user to manually add something like the following lines to `lib.rs`:
```rust
use generic::*;
pub mod generic;
```
Otherwise compilation will fail with errors like the following:
```sh
error[E0433]: failed to resolve: maybe a missing crate `FieldReader`?
--> src\port_1_2\p2ifg.rs:111:25
|
111 |         P2IFG2_R(crate::FieldReader::new(bits))
|                         ^^^^^^^^^^^ maybe a missing crate `FieldReader`?
```
This patch automates adding the above code.
=> Emit code to bring generic module into scope when using `-g` option.

CHANGELOG.md, src/generate/register.rs, src/util.rs
=> don't add underscore to end of "is_keyword"

CHANGELOG.md, src/generate/generic.rs
As 0 is not always correct value, `write_with_zero` can't be safe for all registers.
=> unsafe write_with_zero

CHANGELOG.md, src/generate/device.rs
related to #507 
r? @adamgreig
=> move interrupt generation after generic file

CHANGELOG.md, src/generate/device.rs, src/lib.rs, src/main.rs
Currently projects like stm32-rs have to strip out all the attributes during build to create a file suitable for use as a module. This PR adds a new `-m` switch instead, which causes a `mod.rs` file to be created without the inner attributes or the `pub mod generic`/`use generic::*` lines which would live in the top-level `lib.rs`.
=> Add -m switch to create a module instead of a lib

CHANGELOG.md, src/generate/peripheral.rs, src/util.rs
=> support for alternateGroup registers

CHANGELOG.md, Cargo.toml, README.md
=> Bump version to 0.18 and add missing CHANGELOG.md entries

src/generate/register.rs
All three appear to be trivial wrappers, making the inline useful.
These showed up inspecting the assembly for an interrupt handler requiring sub-µs turn-around times, so fairly critical for that application.
=> Add `#[inline(always)]` to three generated methods.

CHANGELOG.md, src/generate/peripheral.rs
`cluster_size_in_bits` was ignoring array information, leading to incorrect padding with nested clusters.
I noticed this as incorrect padding on the three SARs in PASS0 on the Cypress cyt4bb. (The .svd for this requires registration on the Cypress website.)
It also shows up as incorrect padding on the TCPWM0 in the Cypress PSOC6_04 (svd at https://github.com/cypresssemiconductorco/psoc6pdl/blob/master/devices/svd/psoc6_04.svd)
E.g., for the PSOC TCPWM0, the diffs on the generated code from this change are:
```
diff --git a/src/tcpwm0.rs b/src/tcpwm0.rs
index 678d146..7165c46 100644
--- a/src/tcpwm0.rs
+++ b/src/tcpwm0.rs
@@ -3,7 +3,7 @@
pub struct RegisterBlock {
#[doc = "0x00 - Group of counters"]
pub grp0: GRP,
-    _reserved1: [u8; 32640usize],
+    _reserved1: [u8; 31744usize],
#[doc …
```
=> Be more careful computing the size of an array Cluster.

CHANGELOG.md, src/util.rs
=> multiline descriptions

CHANGELOG.md, src/generate/interrupt.rs, src/main.rs
This PR is a proposal to address #526 . 
`__EXTERNAL_INTERRUPTS` is the symbol used since `__INTERRUPTS` is used by [riscv-rt](https://github.com/rust-embedded/riscv-rt/blob/47ece5f5163a2e38ce5e4685b5d3145713d7954a/src/lib.rs#L505)
I think it fits because the peripheral interrupts are supposed to be pending through the external interrupt. 
This provides hals with information to manage interrupt request. either through a PLIC or trough the vectored interrupt when that is implemented (in [riscv-rt](https://github.com/rust-embedded/riscv-rt/issues/1) i suppose).
Remarks welcome
=> add device.x  for riscv targets, and provides __EXTERNAL_INTERRUPTS

CHANGELOG.md, src/generate/peripheral.rs
Adds an alias to the base module to allow for multiple level of `deriveFrom`.
=> Allow multiple level of deriveFrom peripherals.

src/generate/peripheral.rs, src/generate/register.rs, src/lib.rs
Running `cargo +nightly clippy`, I noticed a few complaints about unnecessary borrows.  Remove those. Clippy now has no complaints either on stable or nightly.
Still builds with stable, and running on a few SVD files, no changes (except for version info).
=> Remove unnecessary borrows.

.github/bors.toml, .github/workflows/ci.yml, CHANGELOG.md, README.md, ci/script.sh, src/generate/interrupt.rs
* Switch to bare-metal 1.0.0
* Use xtensa-lx `InterruptNumber` trait
* Update CI script
=> Xtensa updates

CHANGELOG.md, src/generate/register.rs
When the mask has the same size as the parent register of a field, then
a mask is not required. This removes the clippy warnings/errors where
for example an operation of inverting a mask results in zero
```
error: this operation will always return zero. This is likely not the intended outcome
|
61 |         self.w.bits = (self.w.bits & !0xffff_ffff) | (value as u32 & 0xffff_ffff);
|                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
```
or when the operation of using a mask is ineffective.
```
warning: the operation is ineffective. Consider reducing it to `value as u32`
|
61 |         self.w.bits = (self.w.bits & !0xffff_ffff) | (value as u32 & 0xffff_ffff);
|                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
```
=> Don't use a mask when not needed

CHANGELOG.md, src/generate/register.rs
Currently field modifications aren't fully inlined
=> add `#[inline(always)]` to register field reader constructors

CHANGELOG.md, src/generate/device.rs, src/generate/peripheral.rs, src/main.rs, src/util.rs
Just a small attempt to make `svd2rust` print more useful information if something goes wrong in the TokenStream generation, or in general
- More debug output in case something goes wrong in the TokenStream generation
- Some info output in the main
I like how the `svd` XML parser handles errors by passing an Error Enum with a node ID up which can be used by one central error handler to print diagnostic information. I don't think it can be done like that here, so I simply print out some locally available information (peripheral name, register name etc.) as the error is propagated
=> Better error handling

CHANGELOG.md, src/generate/peripheral.rs
=> Fix register & cluster derive

CHANGELOG.md, src/generate/device.rs, src/generate/peripheral.rs
The application already has log levels and these additional logs will be disabled by default. They can be helpful when debugging something or tracing where an error/warning happens
=> Added debug and trace output

CHANGELOG.md, src/generate/register.rs
This pull request contains two fixes:
1. New line separators are now rendered in enumerated values. 
2. Multi line field descriptions are now rendered correctly in write and read registers.
This issue happened because the original code accidentally unescaped and respaced twice in field parse proccess. It uses escaped description [L292](https://github.com/rust-embedded/svd2rust/compare/master...luojia65:fix-new-line?expand=1#diff-ff493acd6701940416e9725ce824c71d3039b5c56efc3721cf15d1688b3f7deaL292) as input, but in `desctiption_with_bits` function later [L1001](https://github.com/rust-embedded/svd2rust/compare/master...luojia65:fix-new-line?expand=1#diff-ff493acd6701940416e9725ce824c71d3039b5c56efc3721cf15d1688b3f7deaL1001 ) it unescaped again, resulting in loss of new line separators …
=> Fixes in multi line description generation

CHANGELOG.md, src/generate/register.rs
The 'bits' method of register writers can be safe if:
* there is a single field that covers the entire register
* that field can represent all values
=> Generate safe bits writers when possible

.github/workflows/ci.yml
See https://github.com/esp-rs/xtensa-lx/issues/14 and https://github.com/rust-embedded/svd2rust/pull/564#issuecomment-1011606835
=> Temporarily disable Espressif in CI until fixed upstream

CHANGELOG.md, src/generate/register.rs
In #563, we noticed that converting fields' names to snake cases before replacing the suffix caused the generated methods not to satisfy the snake case. This PR fixes this issue.
Use `util::replace_suffix(&f.name, suffix).to_sanitized_snake_case()` instead of `util::replace_suffix(&f.name.to_sanitized_snake_case(), suffix)` when generating methods of fields.
=> fix: Replace suffix before converting to snake case

CHANGELOG.md, src/generate/register.rs
=> don't cast if not use_mask

CHANGELOG.md, src/generate/device.rs
A small change to the MIPS/PIC32 target so that the `#[interrupt]` attribute macro can be used.
=> add re-export of mips_rt::interrupt for MIPS

.github/workflows/ci.yml, ci/script.sh
Reverts https://github.com/rust-embedded/svd2rust/pull/565
=> Re-enable Espressif (merge once upstream is fixed)

CHANGELOG.md, src/generate/interrupt.rs
r? @burrbull
Yet another small MIPS fix in addition to yesterday's change. Sorry for submitting two separate PR instead of a single one. I did not realize that the interrupt macro can cause name clashes when including multiple device support modules into a single crate. I discovered this problem when trying to build the docs.
=> disable the interrupt macro for MIPS as well

CHANGELOG.md, ci/script.sh, src/lib.rs
Crate versions must be `0.3.0` or higher now; minor version `0.2.0` and below is unsupported due to (among other things) bumping to bare-metal `1.0.0` and [using](https://github.com/rust-lang/rust/pull/93219) Rust inline assembly to implement useful operations.
=> Bring documentation on MSP430 up to date.

.github/workflows/ci.yml, CHANGELOG.md, ci/script.sh, src/generate/peripheral.rs
=> array accessors

CHANGELOG.md, src/util.rs
PR to fix the problem explained in [issue 585](https://github.com/rust-embedded/svd2rust/issues/585)
=> added dyn keyword to KEYWORDS in sanitize_keyword

CHANGELOG.md, ci/script.sh, ci/svd2rust-regress/src/svd_test.rs, ci/svd2rust-regress/src/tests.rs
The CI and `rust-regress` tests for Espressif devices were quite out of date, so I've updated both to use the official SVDs and the most recent dependencies. In addition to the ESP32 the ESP32-C3/S2/S3 are now all checked.
=> Use the official Espressif SVDs for testing, check additional chips

CHANGELOG.md, src/generate/register.rs, src/main.rs, src/util.rs
without and with `--pascal_enum_values` option
related: #85
r?adamgreig
=> optional PascalCase for Enum values

CHANGELOG.md, src/generate/array_proxy.rs, src/generate/device.rs, src/generate/peripheral.rs, src/util.rs
- generate ArrayProxy of peripherals when const_generic is true
- generate separate struct of peripherals when const_generic is false
close issue: #492
**Notice:** This is my first try of implement this feature. Please provide suggestions for this PR to better implement this feature.
This PR aims to achieve what issue #492 is asking for. This PR implements a basic try of generating codes depending on the `const_generic` flag.
Let's say we have an svd file with descriptions of peripherals like this:
```XML
<peripheral>
<dim>2</dim>
<dimIncrement>0x100</dimIncrement>
<name>PTEST[%s]</name>
<groupName>PGroup</groupName>
<baseAddress>0x20000000</baseAddress>
<addressBlock>
<offset>0</offset>
<size>0x100</size>
<usage>registers</usage>
</addressBlock>
<registers>
...
</registers>
</peripheral> …
```
=> add code generation support of peripheral arrays

CHANGELOG.md, src/generate/array_proxy.rs
- Don't check `is_empty` on `ArrayProxy`
- Don't check effect of `[(); C][index]` in `Index` trait
=> style: disable two clippy warnings in array_proxy

CHANGELOG.md, src/generate/register.rs
=> read action

CHANGELOG.md, src/generate/generic.rs, src/generate/register.rs
Instead of #541 
~~Require #598~~
=> ModifiedWriteValues for 1-bit fields

.github/workflows/release.yml, CHANGELOG.md
- Compress binaries for Linux and MacOS
- Extract the corresponding section in CHANGELOG and attach it to the release
- Add the date to the title
=> ci: add date and changelog to pre-release

.github/workflows/ci.yml, CHANGELOG.md, Cargo.toml, README.md, src/lib.rs, src/util.rs
Users can now disable binary dependencies if they don't need them, closes #618.
I think we could also make JSON and YAML optional and keep them enabled by default. What do you think?
=> Make binary dependencies optional

CHANGELOG.md, src/generate/register.rs
Alternative to #621 
Reverts [760670616ed807041767cade52518291c810177c](https://github.com/rust-embedded/svd2rust/pull/598/commits/760670616ed807041767cade52518291c810177c)
Advantages:
- easier generation logic, identical for single fields and field arrays (less potential bugs)
- easier to integrate #612
- less boilerplate, faster compilation
Disadvantages:
- as writer not attached to offsets, not obvious meaning of writer
- bigger firmware in debug mode? (need check)
=> field writer's always generic

CHANGELOG.md, src/generate/device.rs, src/generate/interrupt.rs, src/generate/peripheral.rs, src/generate/register.rs, src/util.rs
This pull request is the first part of https://github.com/rust-embedded/svd2rust/pull/612. It merges all `ToSanitizedXxxCase` traits in one `ToSanitizedCase` trait. It also replace all use of upper cases into constant cases, in case the source file did not provide underline between words. It rename variables related to cases, for example `name_sc` to `name_snake_case` to be explict.
The changed code merges original case conversation traits into one trait:
```rust
/// Convert self string into specific case without overlapping to svd2rust internal names
pub trait ToSanitizedCase {
/// Convert self into PascalCase.
///
/// Use on name of enumeration values.
fn to_sanitized_pascal_case(&self) -> Cow<str>;
/// Convert self into CONSTANT_CASE.
///
/// Use on name of reader structs, writer …
```
=> Use one trait for all cases; use constant case for structures

CHANGELOG.md, src/generate/register.rs
~Marked as draft: this pull request depends on https://github.com/rust-embedded/svd2rust/pull/626, and should be merged after that pull request is merged.~ Ready for review as #626 is merged.
This pull request is a rework to https://github.com/rust-embedded/svd2rust/pull/612; commits in this pull request only considers enumeration name other than writer structure and reader structure. Names to those two proxy structures are yet to be discussed.
svd2rust has a good mechanism to parse enumeratedValues into Rust enums. However, current code would pick name of the first field the enum resides, and use pub type to re-export it into other names.
SVD files provide `name` field in enumeratedValues, this commit make use of them to name the Rust enums it generated. After this commit, more …
=> Rework: Enum typename considering name in enumeratedValues

.github/workflows/ci.yml, CHANGELOG.md, Cargo.toml, ci/script.sh, src/generate/device.rs, src/generate/peripheral.rs, src/generate/register.rs, src/util.rs
Should fix #528 #610 #623 #625
=> use svd-parser Index

CHANGELOG.md, src/generate/peripheral.rs, src/generate/register.rs, src/util.rs
+ construct pathes manually instead of parse
=> register & cluster aliases instead of clone when derive

CHANGELOG.md, ci/svd2rust-regress/src/svd_test.rs, src/generate/device.rs, src/lib.rs
- `cortex_m` https://github.com/rust-embedded/cortex-m/pull/447
- `msp430` https://github.com/rust-embedded/msp430/issues/13
- `riscv` https://github.com/rust-embedded/riscv/pull/110
-  `xtensa_lx` https://github.com/esp-rs/xtensa-lx/issues/20, https://github.com/esp-rs/esp-hal/pull/151
- `mips_mcu` https://github.com/kiffie/pic32-rs/issues/5
=> Use `critical_section` for `Peripherals::take`.

CHANGELOG.md, src/lib.rs
The improvements are twofold:
1. Preemptively state that `msp430` and `msp430-rt` 0.4.x are required. Neither are released as of this writing, but will be soon; they will use the `critical_section` crate.
2. Improve describing how to generate an MSP430 SVD in the first place.
=> Improve MSP430 documentation.

CHANGELOG.md, src/generate/peripheral.rs
Added self:: when referencing submodule to avoid ambiguity fix issue https://github.com/rust-embedded/svd2rust/issues/657
=> Fixing compilation error when re-exporting module with same name as a Rust package.

CHANGELOG.md, src/generate/device.rs
This lint has been removed in Rust, see: #669 . We remove it here to avoid compile warnings.
Before this pull request, every peripheral access crate this software generates will emit following warning upon compilation:
```
warning: lint `const_err` has been removed: converted into hard error, see issue #71800 <https://github.com/rust-lang/rust/issues/71800> for more information
--> src\lib.rs:3:9
|
3 | #![deny(const_err)]
|         ^^^^^^^^^
|
= note: `#[warn(renamed_and_removed_lints)]` on by default
```
=> fix: remove lint #![deny(const_err)]

CHANGELOG.md, src/lib.rs
May need to add more details
close #679
=> docs: brief intro to `critical-section`

CHANGELOG.md, build.rs, src/generate/interrupt.rs, src/generate/peripheral.rs, src/generate/register.rs, src/lib.rs
In the previous PR #675, some cases of unnecessary casting are eliminated. However, if there is a big field (bigger than 16) with offset, there is still unnecessary generated casting. This PR fixes this case and adjusts the code according to clippy.
=> Not cast if unnecessary

.github/workflows/ci.yml, CHANGELOG.md, ci/script.sh, ci/svd2rust-regress/src/svd_test.rs, src/generate/generic_msp430_atomic.rs, src/lib.rs
=> Fix generated code for MSP430 atomics

CHANGELOG.md, Cargo.toml, src/generate/peripheral.rs, src/generate/register.rs
Solution 2 for #660 which pre-parses ERC type names and provides expansion information to the render functions. Works great with a few SVDs from the [Renesas RA DFP](https://www2.renesas.eu/Keil_MDK_Packs/Renesas.RA_DFP.4.0.0.pack) which tend to use disjoint arrays quite frequently.
=> Disjoint arrays

CHANGELOG.md, src/generate/peripheral.rs
Closes #660. Compares register properties and fields of regex-matched register names to decide if implicitly deriving is possible. I could use some help with the CI integration for vendor Renesas. See [ra-rs/ra](https://github.com/ra-rs/ra) for SVDs.
=> Compare contents before deriving

CHANGELOG.md, src/generate/peripheral.rs
While working on R7FA6M5BH.svd I found that the generated code does not compile because P0%sPFS_BY got thrown away while implicitly deriving registers. Looking through the debug log I found this:
```
[DEBUG svd2rust::generate::device] Rendering peripheral PFS
[DEBUG svd2rust::generate::peripheral] Checking derivation information
[DEBUG svd2rust::generate::peripheral] register P009PFS_BY implicitly derives from P00%sPFS_BY
[DEBUG svd2rust::generate::peripheral] register P010PFS implicitly derives from P0%sPFS
[DEBUG svd2rust::generate::peripheral] register P010PFS_HA implicitly derives from P0%sPFS_HA
[DEBUG svd2rust::generate::peripheral] register P010PFS_BY implicitly derives from P0%sPFS_BY
[DEBUG svd2rust::generate::peripheral] register P0%sPFS_BY implicitly derives from P00%sPFS_BY …
```
=> Fix dangling implicit derives

.github/workflows/ci.yml, CHANGELOG.md, Cargo.toml, README.md, src/generate/interrupt.rs, src/generate/peripheral.rs, src/generate/register.rs, src/util.rs
Close #710 
The fix escapes only very basic chars <> and & to be as much less intrusive.
The fix could be implement without a new dependencies but more escaping may be required in the near future.
=> Escape <> and & symbol in doc attributes.

CHANGELOG.md, src/generate/interrupt.rs, src/util.rs
This change introduces a new config field that allows `svd2rust` to target which linker sections get assigned to the `__INTERRUPTS` static, with reasonable defaults.
Previously on RISC-V, the choice was always left up to the compiler, and it seemed to always pick `.rodata`. Unfortunately, in my context, that meant placing the LUT in a memory range that had a lot of highly variable latency, which cost not just time but predictability in servicing interrupts.
With this change in place, I'm able to target a particular section (e.g. `.data`, or `.trap.rodata`) for the placement of the static, which grants more granular control over the ultimate loaded memory address.
For the full details about the problem, please see: https://github.com/esp-rs/esp-hal/pull/534/commits/e29f3d547dc210e1b73313be6 …
=> feat: configurable link section attribute for irqs

CHANGELOG.md, src/generate/peripheral.rs, src/generate/register.rs, src/lib.rs, src/main.rs, src/util.rs
contributes towards #48 
Notes:
- I've only run this with esp (esp32/esp32s3) pacs
- I'd love some feedback on where I've implemented this and if there is a cleaner way
=> implement Debug for readable fields of registers

.github/bors.toml, .github/workflows/ci.yml
=> run ci on merging instead of push

CHANGELOG.md, src/generate/device.rs, src/lib.rs, src/main.rs, src/util.rs
similar to `impl_debug_feature`
=> atomics features in generated code

.github/workflows/ci.yml, CHANGELOG.md, ci/script.sh, src/generate/generic.rs, src/generate/generic_atomic.rs, src/generate/register.rs, src/main.rs, src/util.rs
=> generic REG in field writers

.github/workflows/ci.yml, CHANGELOG.md, ci/script.sh, src/generate/generic_atomic.rs
=> fix atomics feature

CHANGELOG.md, src/generate/peripheral.rs, src/lib.rs
This is more convenient than the `Peripherals::steal()`
=> Add steal() for each peripheral.

.github/workflows/ci.yml, CHANGELOG.md, Cargo.toml, README.md, src/generate/register.rs
partially fixes #745 
need more tests
cc @kossnikita
=> fix field derive

CHANGELOG.md, src/generate/array_proxy.rs, src/generate/generic.rs, src/generate/peripheral.rs
=> array-proxy for disjoint arrays

CHANGELOG.md, src/generate/generic.rs, src/generate/register.rs
This is retry of one of my old experiments.
It does 2 things:
1. Moves `offset` from field writer generic to struct field.
2. Always index field array from 0 (slightly confusing but much easier  to work).
Generated code is much simpler.
The main advantage is you can now simply use `.write(|w| w.fname(3).set_bit()` for write/modify field arrays (previously only reading was accepted) same as `.write(|w| w.fname3().set_bit()`.
The main disadvantage is bigger firmware size in debug mode.
cc @kossnikita, @therealprof  and anyone who want to help.
I tried several examples from `stm32f4xx-hal`:
```
before PR vs after PR
blinky-timer-irq  41984/1172 vs 42628/1172
pwm-sinus         49672/8628 vs 50608/8632
rtc-alarm         63704/4680 vs 65648/4680
rtic-usart-shell 88024/17548 vs 88904/17548
``` …
=> writer offset as a struct field

CHANGELOG.md, Cargo.lock, Cargo.toml, src/generate/peripheral.rs, src/generate/register.rs
Closes #172
This is usefull for (reading) fields like this:
For such fields changes look like:
=> support of default enum value

.github/workflows/ci.yml, CHANGELOG.md, ci/script.sh, src/config.rs, src/generate/peripheral.rs, src/generate/register.rs, src/main.rs
=> generate defmt::Format for enums

CHANGELOG.md, src/generate/peripheral/accessor.rs
**TLDR**: This PR contains 1 commit:
1. remove ref (`&`) in `ArrayElemAccessor` to solve the `needless_borrow` warning
---
Currently, the generated code contains two parts:
1. `RawArrayAccessor` takes an argument `n` and returns ref
2. `ArrayElemAccessor` wraps `RawArrayAccessor`
```rust
// An example of generated code
#[doc = "0x58..0x74 - EMAC MAC Address High Register"]
#[inline(always)]
pub const fn emac_addr_high(&self, n: usize) -> &EMAC_ADDR_HIGH {
#[allow(clippy::no_effect)]
[(); 7][n];
unsafe { &*(self as *const Self).cast::<u8>().add(88).add(8 * n).cast() }
}
#[doc = "0x58 - EMAC MAC Address High Register"]
#[inline(always)]
pub const fn emac_addr_high1(&self) -> &EMAC_ADDR_HIGH {
&self.emac_addr_high(0)
}
```
It is needless to use `&` in `emac_addr_high1`.
**Consideration**
I …
=> Remove ref in ArrayElemAccessor to solve the `needless_borrow` warning

CHANGELOG.md, src/generate/device.rs, src/generate/peripheral.rs, src/lib.rs
I had a problem in my SVD file, but I got quite non-specific error: 'Cannot render SVD device'. In order to debug I rewrote error messages to understand the problem. Now it looks like this:
```
called `Result::unwrap()` on an `Err` value: Cannot render SVD device
Caused by:
0: can't render peripheral 'FortiMac', group 'No group name'
1: can't render register 'HASH'
2: can't convert 512 bits into a Rust integral type
```
=> Beautify error messages

CHANGELOG.md, Cargo.lock, Cargo.toml, src/config.rs, src/generate/device.rs, src/generate/interrupt.rs, src/generate/peripheral.rs, src/generate/register.rs, src/main.rs, src/util.rs
This PR doesn't add new cli options (yet?). But you can pass options by config:
```
❯ cat svd2rust.toml 
make_mod = true
generic_mod = true
strict = true
pascal_enum_values = true
max_cluster_size = true
atomics = true
atomics_feature = "atomics"
debug_impl = true
defmt_impl = "defmt"
reexport_core_peripherals = true
reexport_interrupt = true
[ident_formats.register_spec]
case = "constant"
suffix = "rs"
[ident_formats.enum_name]
case = "constant"
[ident_formats.enum_write_name]
case = "constant"
prefix = "w"
[ident_formats.field_reader]
case = "constant"
suffix = "r"
[ident_formats.field_writer]
case = "constant"
suffix = "w"
```
cc @Emilgardis what do you think?
This should not be a breaking change.
=> Custom prefix/case/suffix for identifiers

CHANGELOG.md, src/generate/peripheral/accessor.rs
fixes #798
same fix as done in #789 which was caused by #775
=> fix missing move in register/cluster array iter closure

CHANGELOG.md, src/config.rs, src/generate/peripheral.rs, src/main.rs
Hello!
We are working with the FPGA-based project and unlike with micro-controllers all peripherals are dynamic.
In order to swap different devices (described within several SVD files) in a single board we need to be able to move their addresses.
That's why in this PR we added a flag to shift all base addresses provided in SVD.
=> Add `base-address-shift` configuration flag

CHANGELOG.md, src/generate/generic.rs, src/generate/register.rs
**breaking change**
mark `Writable` register with `Safety` marker.
makes `W::bits` always `unsafe` and always present
add safe `W::set` (other name?) synonym for `W::bits`.
=> generic safe/unsafe W::bits

.github/workflows/ci.yml, CHANGELOG.md, src/config.rs, src/lib.rs, src/main.rs
Closes #803 
cc @jonathanpallant, @Emilgardis
=> change case defaults

.github/workflows/diff.yml, ci/svd2rust-regress/src/diff.rs, ci/svd2rust-regress/src/svd_test.rs
Works around https://github.com/rust-lang/cargo/issues/6009#issuecomment-1925445245
also hopefully fixes issues experienced with the member check
=> regress even better

CHANGELOG.md, ci/script.sh, src/config.rs, src/generate/register.rs, src/main.rs
Some refactoring: always generate `reader` and `writer` after `enum`.
=> RWEnum & field refactoring

CHANGELOG.md, src/config.rs, src/generate/register.rs, src/main.rs
Should fix #652 
and #636 with `--field_names_for_enums` enabled.
=> reexport enum

CHANGELOG.md, src/generate/generic.rs, src/generate/register.rs
instead of #825 
This blocks using `variant` method as "safe" replacement for `bits` on fields without `enumeratedValues`.
Also makes `bits` always `unsafe`. Instead adds `set` method for `Safe` fields. (same as was done in 0.32 for register writer).
=> add IsEnum & rm FieldWriterSafe, add set

CHANGELOG.md, src/generate/register.rs
[DebugStruct::field](https://doc.rust-lang.org/std/fmt/struct.DebugStruct.html#method.field) takes `&dyn Debug`. For primitive types it should give same result as `Display`.
=> Debug impl cleanups

CHANGELOG.md, src/generate/register.rs
=> fix enumeratedValues with isDefault only

.github/workflows/ci.yml, CHANGELOG.md, src/generate/peripheral.rs, src/generate/register.rs
Uses `proc_macro2::Group` for token streams delimited with braces.
Resolves: #863
=> generate: use token groups for delimited token streams

CHANGELOG.md, src/generate/generic.rs, src/generate/register.rs
~~need to test first if~~ it works as expected
=> move must_use from methods to generic type

CHANGELOG.md, Cargo.lock, Cargo.toml, ci/script.sh, ci/svd2rust-regress/src/svd_test.rs, src/config.rs, src/config/riscv.rs, src/generate/device.rs, src/generate/mod.rs, src/generate/riscv.rs, src/lib.rs, src/main.rs
This PR uses [my proposed `riscv` SVD section](https://github.com/rust-embedded/svd/pull/265) to generate RISC-V PACs using the [new set of traits in `riscv-pac`](https://github.com/rust-embedded/riscv/pull/211).
In this PR, the `mod interrupt` in RISC-V targets is handled differently, and includes:
- `ExternalInterrupt`s (very similar to current `Interrupt`s)
- `CoreInterrupt`s (this is new, previously it just assumed the peripheral follows the RISC-V standard)
- `Priority` levels (necessary for interfacing standard peripherals with trait bounds)
- `HartId`s (necessary for interfacing standard peripherals with trait bounds).
Also, the PAC does not directly generate all the handlers array and so on. Instead, it relies on macros exposed in `riscv-pac`.
I still need some time to pollish …
=> Use `riscv` section for RISC-V targets

CHANGELOG.md, src/generate/generic_reg_vcell.rs
Discussed in #859.
- `write_and`
- `write_with_zero_and`
- `modify_and`
These functions return a `T`. The writer cannot be returned outside of the closure because the lifetime is constrained to remain within the function body.
My reasons for this change are to allow strong type-state validity:
```rust
let state = rb.reg().write_and(|w| State::set(w.field()));
```
Thanks @burrbull!
=> Arbitrary Return Types for Register Modification Closures

CHANGELOG.md, Cargo.lock, Cargo.toml, src/generate/interrupt.rs, src/generate/peripheral.rs, src/generate/register.rs, src/generate/riscv.rs, src/util.rs
=> rm html_escape

CHANGELOG.md, ci/script.sh, src/generate/generic_reg_vcell.rs
This looks not so beautiful like #738, but almost not breaking and allows to transfer data between writes with unsafe.
```rust
let bits = rcc.apb1rstr().modify(|_, w| w.usart2rst().clear_bit());
rcc.apb1rstr().write(|w| unsafe { // save on 1 read operation
w.bits(bits).usart2rst().set_bit()
});
```
=> return raw value from write/modify

CHANGELOG.md, src/generate/device.rs, src/generate/interrupt.rs, src/generate/riscv.rs
Fixes #880 
cc @MabezDev @romancardenas @Emilgardis
=> add missing defmt impls

CHANGELOG.md, src/generate/interrupt.rs
InterruptNumber is not useful for us because it's meant to provide an interface for CPU interrupts, but it's implemented by svd2rust for peripheral interrupts.
=> Do not implement InterruptNumber for XtensaLx

CHANGELOG.md, src/generate/device.rs
I have been trying an experiment to generate MSP430 PACs automatically like e.g. [stm-rs does](https://github.com/stm32-rs/stm32-rs).
I am blocked on this patch being accepted, which is technically a bug fix.
=> Do not emit inner attributes for MSP430 with make_mod option active.

CHANGELOG.md, ci/script.sh, ci/svd2rust-regress/tests.yml, src/generate/generic.rs
I tested this with v1.76 using the svd2rust-regress tool. Fixes #895
=> lifetime ellision for FieldWriter to fix clippy warning

CHANGELOG.md, ci/svd2rust-regress/README.md, ci/svd2rust-regress/src/diff.rs, ci/svd2rust-regress/src/main.rs, ci/svd2rust-regress/src/svd_test.rs
I used this to test a fix for https://github.com/rust-embedded/svd2rust/issues/895
I fixed a lot of failing tests, however some of them are still failing. I can open an issue for that.
=> Svd2rust regress fixes

CHANGELOG.md, ci/svd2rust-regress/src/github.rs, src/generate/peripheral.rs, src/generate/register.rs
Some more clippy fixes I have found
=> more clippy fixes

CHANGELOG.md, src/generate/device.rs, src/lib.rs
This adds feature gate displays, for example like the ones in the [syn docs](https://docs.rs/syn/latest/syn/).
The generated library only has a few of those, but I find them to be very useful. Fixes https://github.com/rust-embedded/svd2rust/issues/855
=> improve docs of generated library

.github/workflows/ci.yml, CHANGELOG.md, src/generate/generic.rs, src/generate/generic_atomic.rs, src/generate/generic_reg_vcell.rs, src/generate/register.rs, src/util.rs
Advantages:
- more `const`s
- `zero` is more semantically correct then `default`
- cleaner code
Disadvantages:
- `rustdoc` still not good with `const defaults`. Prints 
instead of `const ZERO_TO_MODIFY_FIELDS_BITMAP: u32 = 0` for default value.
cc @Emilgardis
=> use ConstZero instead of Default

CHANGELOG.md, src/generate/interrupt.rs
This was an oversight discovered in https://github.com/esp-rs/esp-hal/issues/2589
=> Make the interrupt table no_mangle on Xtensa

CHANGELOG.md, src/config/riscv.rs
Currently, `riscv-rt` macros use environment variables to capture characteristics of the target (e.g., RV64 vs RV32, vector table alignment...). While `riscv-rt` properly sets a few environment variables in its`build.rs` script for its internals, these environment variables do not outlive the compilation of other crates (e.g., PACs). Thus, PACs, as users of `riscv-rt` macros, must also define the `RISCV_RT_BASE_ISA` environment variable to make sure that the generated code supports vectored mode.
This PR includes this field in the `settings.yaml` file. As ignoring this field may lead to programs hanging, I also included warning messages to recommend that PAC maintainers include this field if their target supports vectored mode.
=> Add `base_isa` setting for RISC-V
